"""Public SDK surface for mAIvn Platform v2.

The root package mirrors the v1 developer-facing API (minus retired Category C
event-plumbing names) as adapters over the v2 internals, unioned with the
v2-native surface. Names present in both v1 and v2 (``MemoryInsight``,
``MemorySkill``) resolve to the v2-native models that the live client returns.
"""

from __future__ import annotations

from maivn_contracts.artifacts import ArtifactRef, OrdinaryArtifactRef, PrivateArtifactRef
from maivn_contracts.scenarios import (
    ChainedEventSource,
    EmailToInvokeSource,
    ExternalConnectionEventSource,
    FireTriggerToolSource,
    ManualSource,
    MemoryEventSource,
    ReplyConversationSource,
    RetryPolicy,
    ScheduleSource,
    SLATimerSource,
    StorageEventSource,
    TriggerOptions,
    TriggerSource,
    WebhookSource,
)

from maivn.__version__ import __version__
from maivn._internal.artifacts import (
    ArtifactDownload,
    ArtifactListPage,
    ArtifactMetadata,
    ArtifactPreview,
)
from maivn._internal.automatic_vault import LocalVaultConfig, VaultSetupError
from maivn._internal.client import Client
from maivn._internal.compat.base import BaseScope
from maivn._internal.compat.billing import (
    BillingCurrentUsage,
    BillingPlan,
    BillingUsage,
    BillingUsageApiKey,
    BillingUsageBreakdown,
    BillingUsageProject,
    BillingUsageTotals,
)
from maivn._internal.compat.configuration import (
    ClientBuilder,
    ConfigurationBuilder,
    MaivnConfiguration,
    get_configuration,
)
from maivn._internal.compat.decorators import (
    compose_argument_policy,
    depends_on_agent,
    depends_on_await_for,
    depends_on_interrupt,
    depends_on_private_data,
    depends_on_reevaluate,
    depends_on_tool,
    requires_producer_reference,
    tool_output,
    toolify,
    toolset,
)
from maivn._internal.compat.interrupts import (
    AgentGenerated,
    FollowupInputHandler,
    FollowupOption,
    FollowupQuestion,
    FollowupQuestionsConfig,
    default_terminal_followup,
    default_terminal_interrupt,
)
from maivn._internal.compat.logging import configure_logging, get_logger
from maivn._internal.compat.mcp import (
    MCPAutoSetup,
    MCPServer,
    MCPSoftErrorHandling,
    ToolOverride,
)
from maivn._internal.compat.memory_read_models import (
    MemoryInsightOrigin,
    MemoryInsightType,
    MemoryPersistenceCeiling,
    MemoryResource,
    MemoryResourceBindingType,
    MemoryResourceDetail,
    MemoryResourceStatus,
    MemorySkillOrigin,
    MemorySkillStatus,
    MemoryUnboundResourceCandidate,
    OrganizationMemoryPolicy,
    OrganizationMemoryPurgeResult,
    ProjectMemoryResources,
)
from maivn._internal.compat.options import (
    AuthMode,
    FinalOutputMode,
    MemoryAssetsConfig,
    MemoryConfig,
    MemoryGraphExtractionConfig,
    MemoryInsightExtractionConfig,
    MemoryLevel,
    MemoryPersistenceMode,
    MemoryResourceConfig,
    MemoryRetrievalConfig,
    MemorySharingScope,
    MemorySkillConfig,
    MemorySkillExtractionConfig,
    ModelChoice,
    ModelConfig,
    ModelConfigPart,
    ModelTier,
    OrchestrationMode,
    PlanningChoice,
    PlanningTier,
    ProviderCapability,
    ProviderMetadata,
    SessionExecutionConfig,
    SessionOrchestrationConfig,
    StopStrategy,
    StructuredOutputConfig,
    SwarmAgentConfig,
    SwarmConfig,
    SystemToolsConfig,
)
from maivn._internal.compat.permissions import (
    PERMISSION_FLAG_NAMES,
    PermissionFlag,
    PermissionSet,
    require_permissions,
)
from maivn._internal.compat.privacy import (
    HIPAA_SAFE_HARBOR_CATEGORIES,
    PIIWhitelist,
    PIIWhitelistEntry,
    PrivateData,
    RedactedMessage,
    RedactionPreviewRequest,
    RedactionPreviewResponse,
)
from maivn._internal.compat.scheduling import (
    AtSchedule,
    BackpressurePolicy,
    CronInvocationBuilder,
    CronSchedule,
    IntervalSchedule,
    JitterDistribution,
    JitterSpec,
    MisfirePolicy,
    OverlapPolicy,
    Retry,
    RetryBackoff,
    RunRecord,
    RunStatus,
    Schedule,
    ScheduledJob,
    list_jobs,
    stop_all_jobs,
)
from maivn._internal.compat.tooling import ToolingScopeMixin, toolify_options, toolset_options
from maivn._internal.config import ClientConfig
from maivn._internal.errors import (
    AsyncContextError,
    ConfigurationError,
    DurableBoundaryRefusedError,
    MaivnHTTPError,
    MaivnSDKError,
    ResourceRegistrationError,
)
from maivn._internal.memory import (
    MemoryDeleteResponse,
    MemoryEnrichmentReceipt,
    MemoryInsight,
    MemoryInsightCreate,
    MemoryInsightUpdate,
    MemoryScope,
    MemoryScopeRequest,
    MemorySkill,
    MemorySkillCreate,
    MemorySkillStep,
    MemorySkillUpdate,
)
from maivn._internal.models import (
    ApprovalDecision,
    InvokeResponse,
    ProviderModelUsage,
    ProviderUsage,
    RunOptions,
    StreamEvent,
    ThreadAccepted,
    ThreadCheckpoint,
    ThreadState,
)
from maivn._internal.plan_limits import PlanLimitExceededError
from maivn._internal.private_artifacts import (
    PrivateArtifactAuthorizationDeniedError,
    PrivateArtifactEffectFailedError,
    PrivateArtifactError,
    PrivateArtifactGrantExpiredError,
    PrivateArtifactsClient,
    PrivateArtifactTimeoutError,
    TransientVaultClientProof,
)
from maivn._internal.private_data_store import (
    EncryptedFilePrivateDataStore,
    InMemoryPrivateDataStore,
    PrivateDataStore,
)
from maivn._internal.resources import (
    ResourceDeleteResponse,
    ResourcePatch,
    ResourceRecord,
    ResourceScopeRequest,
    ResourceUploadOptions,
)
from maivn._internal.scope import Agent as _Agent
from maivn._internal.scope import Swarm as _Swarm
from maivn._internal.serving import (
    ServingEvent,
    ServingListener,
    ServingSession,
)
from maivn._internal.skills import (
    Skill,
    SkillChildNotFoundError,
    SkillCycleError,
    SkillFrontmatterError,
    SkillMarkdownError,
    SkillScopeRequest,
    SkillSet,
    SkillStep,
    parse_skill_markdown,
)
from maivn._internal.thread import BoundThread
from maivn._internal.triggers import (
    Trigger,
    TriggerFireReceipt,
    TriggerInvocationBuilder,
    stable_trigger_ids,
)


class Agent(_Agent, ToolingScopeMixin, BaseScope):
    """V1-compatible agent public class with BaseScope and tooling helpers."""


class Swarm(_Swarm, ToolingScopeMixin, BaseScope):
    """V1-compatible swarm public class with BaseScope and tooling helpers."""


__all__ = [  # noqa: RUF022 - Keep v1 public export order for compatibility.
    'LocalVaultConfig',
    'VaultSetupError',
    '__version__',
    # --- v2-native surface (preserved) ---
    'ApprovalDecision',
    'ArtifactDownload',
    'ArtifactListPage',
    'ArtifactMetadata',
    'ArtifactPreview',
    'ArtifactRef',
    'AsyncContextError',
    'BoundThread',
    'ClientConfig',
    'ConfigurationError',
    'DurableBoundaryRefusedError',
    'InvokeResponse',
    'MaivnHTTPError',
    'PlanLimitExceededError',
    'MaivnSDKError',
    'MemoryDeleteResponse',
    'OrdinaryArtifactRef',
    'PrivateArtifactRef',
    'PrivateArtifactAuthorizationDeniedError',
    'PrivateArtifactEffectFailedError',
    'PrivateArtifactError',
    'PrivateArtifactGrantExpiredError',
    'PrivateArtifactsClient',
    'PrivateArtifactTimeoutError',
    'ProviderModelUsage',
    'ProviderUsage',
    'MemoryInsightCreate',
    'MemoryInsightUpdate',
    'MemoryScope',
    'MemoryScopeRequest',
    'MemorySkillCreate',
    'MemorySkillStep',
    'MemorySkillUpdate',
    'EncryptedFilePrivateDataStore',
    'InMemoryPrivateDataStore',
    'PrivateDataStore',
    'ResourceDeleteResponse',
    'ResourcePatch',
    'ResourceRecord',
    'ResourceRegistrationError',
    'ResourceScopeRequest',
    'ResourceUploadOptions',
    'RunOptions',
    'ServingEvent',
    'ServingListener',
    'ServingSession',
    'Skill',
    'SkillChildNotFoundError',
    'SkillCycleError',
    'SkillFrontmatterError',
    'SkillMarkdownError',
    'SkillScopeRequest',
    'SkillSet',
    'SkillStep',
    'StreamEvent',
    'ThreadAccepted',
    'ThreadCheckpoint',
    'ThreadState',
    'TransientVaultClientProof',
    'Trigger',
    'TriggerFireReceipt',
    'TriggerInvocationBuilder',
    'stable_trigger_ids',
    'ChainedEventSource',
    'EmailToInvokeSource',
    'ExternalConnectionEventSource',
    'FireTriggerToolSource',
    'ManualSource',
    'MemoryEventSource',
    'ReplyConversationSource',
    'RetryPolicy',
    'ScheduleSource',
    'SLATimerSource',
    'StorageEventSource',
    'TriggerOptions',
    'TriggerSource',
    'WebhookSource',
    'parse_skill_markdown',
    # --- v1-compatible surface (restored as adapters) ---
    'configure_logging',
    'get_logger',
    'BackpressurePolicy',
    'compose_argument_policy',
    'depends_on_agent',
    'depends_on_await_for',
    'depends_on_private_data',
    'depends_on_interrupt',
    'depends_on_reevaluate',
    'depends_on_tool',
    'requires_producer_reference',
    'tool_output',
    'toolify',
    'toolify_options',
    'toolset',
    'toolset_options',
    'Agent',
    'BaseScope',
    'Client',
    'ClientBuilder',
    'MCPAutoSetup',
    'MCPServer',
    'MCPSoftErrorHandling',
    'Swarm',
    'ToolOverride',
    'OrganizationMemoryPolicy',
    'OrganizationMemoryPurgeResult',
    'MemoryPersistenceCeiling',
    'MemoryResource',
    'MemoryResourceDetail',
    'MemoryResourceBindingType',
    'MemoryResourceStatus',
    'MemorySkill',
    'MemoryEnrichmentReceipt',
    'MemorySkillOrigin',
    'MemorySkillStatus',
    'MemoryInsight',
    'MemoryInsightType',
    'MemoryInsightOrigin',
    'MemoryUnboundResourceCandidate',
    'ProjectMemoryResources',
    'BillingUsage',
    'BillingPlan',
    'BillingCurrentUsage',
    'BillingUsageBreakdown',
    'BillingUsageProject',
    'BillingUsageApiKey',
    'BillingUsageTotals',
    'PERMISSION_FLAG_NAMES',
    'PermissionFlag',
    'PermissionSet',
    'require_permissions',
    'AuthMode',
    'ProviderCapability',
    'ProviderMetadata',
    'HIPAA_SAFE_HARBOR_CATEGORIES',
    'PIIWhitelist',
    'PIIWhitelistEntry',
    'PrivateData',
    'MemoryConfig',
    'MemoryGraphExtractionConfig',
    'MemoryAssetsConfig',
    'MemoryInsightExtractionConfig',
    'MemoryLevel',
    'MemoryPersistenceMode',
    'MemoryResourceConfig',
    'MemoryRetrievalConfig',
    'MemorySharingScope',
    'MemorySkillConfig',
    'MemorySkillExtractionConfig',
    'ModelChoice',
    'ModelConfig',
    'ModelConfigPart',
    'ModelTier',
    'PlanningChoice',
    'PlanningTier',
    'FinalOutputMode',
    'OrchestrationMode',
    'SessionExecutionConfig',
    'SessionOrchestrationConfig',
    'StopStrategy',
    'StructuredOutputConfig',
    'SwarmAgentConfig',
    'SwarmConfig',
    'SystemToolsConfig',
    'RedactedMessage',
    'RedactionPreviewRequest',
    'RedactionPreviewResponse',
    'ConfigurationBuilder',
    'MaivnConfiguration',
    'get_configuration',
    'AgentGenerated',
    'FollowupInputHandler',
    'FollowupOption',
    'FollowupQuestion',
    'FollowupQuestionsConfig',
    'default_terminal_followup',
    'default_terminal_interrupt',
    'AtSchedule',
    'CronInvocationBuilder',
    'CronSchedule',
    'IntervalSchedule',
    'JitterDistribution',
    'JitterSpec',
    'MisfirePolicy',
    'OverlapPolicy',
    'Retry',
    'RetryBackoff',
    'RunRecord',
    'RunStatus',
    'Schedule',
    'ScheduledJob',
    'list_jobs',
    'stop_all_jobs',
]
